package livecanvas;

public interface Constants {
	public static final int EXIT = -1, NEW = 0, OPEN = 1, SAVE = 2,
			BGREF_SET = 300, BGREF_REMOVE = 301, BGREF_BINDEX = 302,
			BGREF_MAKEVISIBLE = 303, BGREF_MAKEINVISIBLE = 304,
			BGREF_MAKESUBVISIBLE = 305, BGREF_MAKESUBINVISIBLE = 306,
			RENDER = 8, PREVIEW = 9, UNDO = 10, REDO = 11, CUT = 12, COPY = 13,
			PASTE = 14, SELECT_ALL = 15, INVERT_SELECTION = 16,
			IMPORT_MESH = 17, SEE_THROUGH = 18, SHOW_MESH = 19, SETTINGS = 20,
			RENDER_SETTINGS = 21, ADD_LAYER = 30, REMOVE_LAYER = 31,
			DUPLICATE_LAYER = 32, MOVEUP_LAYER = 33, MOVEDOWN_LAYER = 34,
			REPARENT_LAYER = 35, GROUP_LAYERS = 36, UNGROUP_LAYER = 37,
			JOIN_LAYERS = 38, INTERSECT_LAYERS = 39, SUBTRACT_LAYERS = 40,
			RENAME_LAYER = 41, CREATE_MESHGRID = 42, ADD_KEYFRAME = 50,
			REMOVE_KEYFRAME = 51, SELECTPREV_KEYFRAME = 52,
			SELECTNEXT_KEYFRAME = 53, MOVEPREV_KEYFRAME = 54,
			MOVENEXT_KEYFRAME = 55, ONIONSKIN_PREV = 56, ONIONSKIN_NEXT = 57,
			TWEEN_KEYFRAMES = 58, PREVIEW_START = 70, PREVIEW_STOP = 71,
			PREVIEW_PAUSE = 72, PREVIEW_PREV = 73, PREVIEW_NEXT = 74;
	public static final int TOOLS_PENCIL = 100, TOOLS_BRUSH = 101,
			TOOLS_PEN = 102, TOOLS_ERASE = 104, TOOLS_FILL = 105,
			TOOLS_SELECT = 106, TOOLS_POINTER = 107, TOOLS_PANZOOM = 108,
			TOOLS_MAGICWAND = 109, TOOLS_SETCONTROLPOINTS = 110;
	public static final int MESH_DRAW = 200, MESH_SET_CONTROLS = 201,
			MESH_MANIPULATE = 202;
	public static final double[] sActionRadius = { 10, 20, 30 };
	public static final int ANGLE_DIVISIONS = 16;
	public static final int ANGLE_DIVISIONS2 = ANGLE_DIVISIONS / 2;
	public static final double ANGLE_STEPSIZE = 2 * Math.PI / ANGLE_DIVISIONS;
	public static final double MOVE_STEPSIZE = 2;
}
